# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.17.1'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    node src/server.js 
    if [ $? -eq 0 ]; then
      echo "Express.js server ran successfully."
      exit 0
    else
      echo "Express.js server encountered an error."
      exit 1
    fi
  displayName: 'Express js server'